### ISSUE TITLE
Synchronised across two devices or copy data to second device.

### ISSUE THREAD

**Issue by Tobyjoe1949** [DennisBauer/RecurringExpenseTracker#374] opened 2024-11-15 22:17 UTC
**Is your feature request related to a problem? Please describe.**
  
  
  **Describe the solution you'd like**
  
  
  **Describe alternatives you've considered, if any**
  
  
  **Additional context**

**Comment by DennisBauer** [comment] 2024-11-16 08:36
@Tobyjoe1949 can you please elaborate and add some more details to the issue? I'm not sure what you're referring to.

**Comment by Tobyjoe1949** [comment] 2024-11-16 09:09
I have the app on my tablet. I will put it on my wife's tablet as well. I will then need to remember when making any changes to update hers as well. By way of example, I use Msecure as password manager on tablet and computer which synchronise 's any changes on either device. This is done on WiFi as i avoid cloud data wherever possible.


________________________________

**Comment by DennisBauer** [comment] 2024-11-16 11:09
Then this is a duplicate of #44, please have a look at the description. You should be able to achieve a sync using the automatic backup and restore.

**Closed** 2024-11-16 11:13 UTC
Labels: duplicate
